### ISSUE TITLE
New commits

### ISSUE THREAD

**Issue by thewaiter** [mbert/etheme-blingbling-e20#2] opened 2017-09-22 14:49 UTC
Hello, I did not find the better way how to communicate. So, I hope you still work with E desktop. 
Here is the screenshot before and after modifications. 
http://forums.bodhilinux.com/index.php?/topic/13328-theme-fixing/page-3

The only issue is elm support. It does not look good. It needs a lot of love :)
Best regards

**Comment by mbert** [comment] 2017-09-22 14:51
Just wrote you a mail. Received it? Then let's continue there.

**Comment by thewaiter** [comment] 2017-09-22 14:55
Great :)
 
Hello again. I am not sure I am skilled enough to continue with elm stuff. Maybe one day I will find more power to study this complex theme topic. It is not for everyone :(
 
Stefan
______________________________________________________________
> Od: Martin Dietze <notifications@github.com>
> Komu: mbert/etheme-blingbling-e20 <etheme-blingbling-e20@noreply.github.com>
> Dátum: 22.09.2017 16:51
> Predmet: Re: [mbert/etheme-blingbling-e20] New commits (#2)
>
Just wrote you a mail. Received it? Then let's continue there.

**Comment by mbert** [comment] 2017-09-22 14:57
Same for me. I just decided to use (and publish) the theme as (incomplete) as it was because there was hardly anything for e20, so that there actually was some benefit in it, even if it's not perfect.

**Comment by thewaiter** [comment] 2017-09-22 14:59
I think the theme is ready for another release. I think, I won't add more fixes. 
BTW: I made some more theming stuff you can find on my git repo :)

**Comment by mbert** [comment] 2017-09-22 15:00
Fine. Will do. I'll put your name into the list in the 'about' box.

**Comment by thewaiter** [comment] 2017-09-22 15:01
Thx :)

**Comment by mbert** [comment] 2017-09-22 15:05
If you're getting more into e20 (seems like most Bodhi users haven't yet made this step) I'd be happy to find your work on e-stuff. I like to switch themes from time to time :)

**Comment by thewaiter** [comment] 2017-09-22 16:26
My main goal is bringing themes mainly for Bodhi Linux users. From time to time I come across some other users wishes and port some stuff for them. Recently I ported my Sticky Notes module for Onlyhuman. The version is not at my git yet. I will do that as soon as possible...

**Comment by mbert** [comment] 2017-09-22 16:48
I hope that e2x will be stable enough for Bodhi soon, so that theming effort no longer results in incompatible branches. Theming e ist complex enough and few enough people contribute. 

Here's the new release on e-stuff (nowadays opendesktop): https://www.opendesktop.org/p/1018484/

**Comment by thewaiter** [comment] 2017-09-23 16:39
Great:)
I count with you and your testing under E20...

**Comment by mbert** [comment] 2017-09-23 19:58
With pleasure. I like these classic, shiny themes. More on Monday.

**Comment by mbert** [comment] 2017-09-25 07:39
Tried it. Looks good. Is there any more to come this week? Just asking before I push out another release.

**Comment by thewaiter** [comment] 2017-09-25 09:23
Don't push please. I can see the elm menu issue (bad color) and huge ugly elm-buttons. Let me look at that. We have enough time... :)

**Comment by mbert** [comment] 2017-09-25 09:26
Fine for me. Note that there can always be a bit of a delay before I can try things out since I don't always have physical access to my e20 desktop.

**Comment by thewaiter** [comment] 2017-09-25 09:30
No problem. As I said plenty of time in our hands. BTW, feel free to contribute to this project in case of your spare time and taste :)

**Comment by mbert** [comment] 2017-09-25 09:32
At the moment time is totally insufficient. Unfortunately I am still a beginner. I hope I can pick up a few tricks from your work :)

**Comment by thewaiter** [comment] 2017-09-25 19:58
Please check all todays commits. Maybe we are close to next release. I am thinking of fixing the genlist.edc but it will be hard as hell.

**Comment by mbert** [comment] 2017-09-25 20:16
Will do tomorrow. I propose to make a release on Wednesday since I won't be able to access my e20 box for two weeks from then on.

**Comment by thewaiter** [comment] 2017-09-25 20:18
OK

**Comment by mbert** [comment] 2017-09-26 07:34
Merged it and installed the result. Looks good so far.

**Comment by mbert** [comment] 2017-09-26 07:43
One thing though, not sure what causes this: After applying the theme I experienced the wallpaper image only being applied on the first desktop. I switched to another theme, it had no such problem. Then back to blingbling, again only the first desktop had the wallpaper. Applied another wallpaper by hand, then checked "use theme wallpaper" again, now things are fine. 

This is a bit strange. Not sure though whether this is not a problem in e.

**Comment by thewaiter** [comment] 2017-09-28 13:54
OK, v 0.9.1. Why not?! 
Let me have some time for next developing. I had some spare time for mountain biking these days. Better than sitting in front of PC :)

**Comment by thewaiter** [comment] 2017-09-28 18:44
No, I have no issues with switching among desktops...

**Comment by mbert** [comment] 2017-09-28 18:45
It may have been caused by display driver issues I have on my system. I'll keep an eye on it.

**Comment by mbert** [comment] 2017-09-28 18:46
Concerning 0.9.1, it's just because I had promised to do so. I won't be able to access my machine for the next two weeks, so all further updates will have to wait.

**Comment by thewaiter** [comment] 2017-09-28 18:51
I see no problem :)

**Comment by thewaiter** [comment] 2017-10-13 18:25
I have noticed, we have no ilist selected item indicator. It is fixed in today's commit
http://www.enlightenment.org/ss/e-59e104e6b73dd2.51655302.jpg

**Comment by thewaiter** [comment] 2017-10-14 17:02
Sorry, I closed this issue by mistake :)

**Comment by mbert** [comment] 2017-10-14 18:20
I have merged it. However I won't be able to test it before end of the week.

**Comment by mbert** [comment] 2017-10-20 14:09
Got your latest changes running here. Everything is looking good.

**Comment by mbert** [comment] 2017-10-23 19:46
Packaged the last changes to version 0.9.2 and published on opendesktop.org

**Comment by thewaiter** [comment] 2017-11-08 09:18
Hello Martin

Just added the menu arrow, which was ugly because of its size. Now it could be fine. Test if your time permits ;)

**Comment by thewaiter** [comment] 2017-11-17 19:27
Hello
Are you able to change the theme preview in opendesktop page? Our theme now looks much better than on the current picture.

**Comment by mbert** [comment] 2017-11-17 19:28
Yes, I can. But I don't have anything better at hand now, so if you've got something nice :)
Otherwise I can make a screenshot on Monday.

**Comment by thewaiter** [comment] 2017-11-17 19:32
No problem preparing the scene here. Or we can use that one on the Bodhi forums? 
https://www.enlightenment.org/ss/e-59c412dc573129.24347380.jpg

**Comment by mbert** [comment] 2017-11-17 19:34
I don't mind. Just tell me which one you'd prefer.

**Comment by thewaiter** [comment] 2017-11-17 19:39
Let's use that one I mentioned. I like it. If you want, make an another shot and add. We can have more pictures.

**Comment by mbert** [comment] 2017-11-17 19:40
Can you give me a quick link? I'm not at my Linux box now.

**Comment by thewaiter** [comment] 2017-11-17 19:41
https://www.enlightenment.org/ss/e-59c412dc573129.24347380.jpg

**Comment by mbert** [comment] 2017-11-17 19:42
(y)

**Closed as completed** 2021-06-20 13:19 UTC
